###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: desafio-capgemini-mysql
      working_dir: /application
      volumes:
        - ./infra:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=bank_db
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "7981:3306"

    webserver:
      image: nginx:alpine
      container_name: desafio-capgemini-webserver
      working_dir: /application
      volumes:
          - ./api:/application
          - ./devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7979:80"

    php-fpm:
      build: devops/php-fpm
      container_name: desafio-capgemini-php-fpm
      working_dir: /application
      volumes:
        - ./api:/application
        - ./devops/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

